image:
  service:
    url: https://image-service.springofficehours.io
  
logging:
  level:
    root: 'off'

spring:
  main:
    banner-mode: 'off'
    web-application-type: 'NONE'
  shell:
    history:
      enabled: 'false'
  threads:
    virtual:
      enabled: true  