image:
  service:
#    url: https://image-service.delightfulgrass-b9313e54.eastus.azurecontainerapps.io
    url: http://localhost:8080/
  
logging:
  level:
    root: 'off'

spring:
  main:
    banner-mode: 'off'
    web-application-type: 'NONE'
  shell:
    history:
      enabled: 'false'  