name: dashaun/spring-office-hours-helper

on:
  workflow_dispatch:
    
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 22.3
          java-version: '17'
          components: 'native-image'

      - name: Build shell
        run: |
          ./mvnw -Pnative -DskipTests clean spring-boot:build-image
          docker tag 